<a href="https://colab.research.google.com/github/aditi-tawade-ai/ML_Projects/blob/main/Age_Income_Clustering/age_%26_income.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
path = '/content/Employee_income_1.csv'
df = pd.read_csv(path)
df[:2]

    Name  Age  Income
0   Amit   27   70000
1  Akash   29   90000

In [ ]:
df.shape

(24, 3)

In [ ]:
df

       Name  Age  Income
0      Amit   27   70000
1     Akash   29   90000
2    Shriya   29   61000
3     Anita   28   62000
4    Sudhir   42  155000
5   Gajanan   39  160000
6    Ranjit   41  162000
7   Jyotsna   38  156000
8    Nitish   36  130000
9     Onkar   35  136000
10    Neeta   37   45000
11   Yogesh   26   48000
12   Aniket   27   51000
13  Digabar   28   49500
14    Nitin   29   53000
15   Shweta   39  165000
16  Shambhu   40   63000
17    Aliza   40   64000
18   Alizya   43   80000
19      Sid   39   82000
20    Abdul   41   58000
21     Riya   38   64000
22      Nik   27   58000
23     John   40  148000